pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AtomixGG/Jenkins-docker.git'
            }
        }
        stage('Build Image') {
            steps {
                sh '''
                    docker build -t jenkins-demo-app:latest .
                '''
            }
        }
        stage('Run Container') {
            steps {
                // ลบ container เก่า ถ้ามี
                sh 'docker rm -f demo-app || true'

                // รัน container บน host จริง
                sh '''
                    docker run -d -p 5000:5000 --name demo-app jenkins-demo-app:latest
                '''
            }
        }
    }
}
